// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Hack-the-Crisis-got-milk/Shops/config"
	"github.com/Hack-the-Crisis-got-milk/Shops/environment"
	"github.com/Hack-the-Crisis-got-milk/Shops/gateway/feedback"
	"github.com/Hack-the-Crisis-got-milk/Shops/routers"
	"github.com/Hack-the-Crisis-got-milk/Shops/routers/api/v1"
	"github.com/Hack-the-Crisis-got-milk/Shops/utils"
)

// Injectors from wire.go:

func InitializeServer() (Server, error) {
	logger, err := utils.NewLogger()
	if err != nil {
		return Server{}, err
	}
	env := environment.NewEnv(logger)
	appConfig, err := config.NewAppConfig(env)
	if err != nil {
		return Server{}, err
	}
	client, err := utils.NewGoogleMapsClient(env)
	if err != nil {
		return Server{}, err
	}
	feedbackClient, err := feedback.NewClient(logger, appConfig)
	if err != nil {
		return Server{}, err
	}
	apiv1Router := v1.NewAPIV1Router(logger, env, appConfig, client, feedbackClient)
	mainRouter := routers.NewMainRouter(logger, apiv1Router)
	server := NewServer(mainRouter, env)
	return server, nil
}
