// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Hack-the-Crisis-got-milk/Shops/environment"
	"github.com/Hack-the-Crisis-got-milk/Shops/routers"
	"github.com/Hack-the-Crisis-got-milk/Shops/utils"
)

// Injectors from wire.go:

func InitializeServer() (Server, error) {
	logger, err := utils.NewLogger()
	if err != nil {
		return Server{}, err
	}
	mainRouter := routers.NewMainRouter(logger)
	env := environment.NewEnv(logger)
	server := NewServer(mainRouter, env)
	return server, nil
}
