// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Hack-the-Crisis-got-milk/Shops/environment"
	"github.com/Hack-the-Crisis-got-milk/Shops/repositories"
	"github.com/Hack-the-Crisis-got-milk/Shops/routers"
	"github.com/Hack-the-Crisis-got-milk/Shops/utils"
)

// Injectors from wire.go:

func InitializeServer() (Server, error) {
	logger, err := utils.NewLogger()
	if err != nil {
		return Server{}, err
	}
	env := environment.NewEnv(logger)
	database, err := utils.NewDatabase(logger, env)
	if err != nil {
		return Server{}, err
	}
	itemGroupRepository, err := repositories.NewItemGroupRepository(database)
	if err != nil {
		return Server{}, err
	}
	mainRouter := routers.NewMainRouter(logger, itemGroupRepository)
	server := NewServer(mainRouter, env)
	return server, nil
}
