version: '2.1'

services:
  shops:
    image: shops:latest
    ports:
      - 8010:8010
    env_file:
      - ../../app.env
    volumes:
      - ../../:/go/src/github.com/Hack-the-Crisis-got-milk/Shops
    networks:
      - internal

networks:
  # internal network for shops services
  internal:
    driver: bridge
    name: internal
